# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='studentname',
            new_name='student',
        ),
    ]
