# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170713_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='bigidearubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BigIdeaRubric'),
        ),
    ]
