# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evidence_bigidearubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='bigidearubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BigIdeaRubric'),
        ),
    ]
