# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170716_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='student',
        ),
        migrations.AlterField(
            model_name='evidence',
            name='done',
            field=models.BooleanField(default=True),
        ),
    ]
