# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170725_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='pkcore',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='evidence',
            name='pkidea',
            field=models.IntegerField(default=1),
        ),
    ]
