# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_first', models.CharField(max_length=30)),
                ('student_last', models.CharField(max_length=30)),
                ('class_list', models.CharField(max_length=1200)),
                ('course_name', models.CharField(max_length=20)),
                ('course_block', models.CharField(max_length=10)),
                ('attend', models.BooleanField(default=True)),
                ('group_size', models.IntegerField(default=3)),
                ('nickname', models.CharField(max_length=20)),
            ],
        ),
    ]
