# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20170730_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='course_block',
            field=models.CharField(choices=[('11', 'Block 1-1'), ('12', 'Block 1-2'), ('13', 'Block 1-3'), ('14', 'Block 1-4'), ('21', 'Block 2-1'), ('22', 'Block 2-2'), ('23', 'Block 2-3'), ('24', 'Block 2-4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='course_name',
            field=models.CharField(choices=[('MA8', 'Math 8'), ('SC10', 'Science 10'), ('PH11', 'Physics 11'), ('PH12', 'Physics 12')], max_length=20),
        ),
    ]
