# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20170731_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first', models.CharField(default='John', max_length=30)),
                ('student_last', models.CharField(default='Smith', max_length=30)),
                ('nickname', models.CharField(default='JohnS', max_length=31)),
                ('attend', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='attend',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='student_first',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='student_last',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='student_name',
        ),
        migrations.AddField(
            model_name='students',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom'),
        ),
    ]
